#!/usr/bin/env python3
"""
Generate Markdown security audit report from Toonic analysis results.

Usage:
    python generate_report.py [--output report.md] [--format markdown]
"""

import argparse
import json
import sqlite3
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any

def load_exchanges(data_dir: Path) -> List[Dict[str, Any]]:
    """Load exchange data from JSONL file."""
    exchanges_file = data_dir / "exchanges.jsonl"
    if not exchanges_file.exists():
        return []
    
    exchanges = []
    with open(exchanges_file, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                try:
                    data = json.loads(line)
                    exchanges.append(data)
                except json.JSONDecodeError:
                    continue
    return exchanges

def load_history(data_dir: Path) -> List[Dict[str, Any]]:
    """Load conversation history from SQLite database."""
    history_db = data_dir / "history.db"
    if not history_db.exists():
        return []
    
    try:
        conn = sqlite3.connect(str(history_db))
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        cursor.execute("""
            SELECT timestamp, role, content, model_used, tokens_used 
            FROM conversation_history 
            ORDER BY timestamp DESC
        """)
        
        history = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return history
    except Exception:
        return []

def generate_markdown_report(exchanges: List[Dict], history: List[Dict], goal: str) -> str:
    """Generate Markdown report from analysis data."""
    
    # Filter for security audit reports
    security_reports = []
    for exchange in exchanges:
        if (exchange.get('event') == 'action' and 
            exchange.get('data', {}).get('action_type') == 'report'):
            content = exchange['data'].get('content', '')
            if any(keyword in content.lower() for keyword in ['security', 'ssl', 'tls', 'vulnerability', 'owasp']):
                security_reports.append(exchange['data'])
    
    # Generate report
    report = f"""# Security Audit Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Goal:** {goal}

## Executive Summary

{len(security_reports)} security analysis reports generated.

"""
    
    if security_reports:
        report += "## Security Findings\n\n"
        for i, rep in enumerate(security_reports, 1):
            confidence = rep.get('confidence', 0.0)
            content = rep.get('content', '')
            affected_files = rep.get('affected_files', [])
            model = rep.get('model_used', 'unknown')
            
            report += f"""### Finding {i}

**Confidence:** {confidence:.2%}
**Model:** {model}

{content}

"""
            if affected_files:
                report += f"**Affected Files:** {', '.join(affected_files)}\n\n"
            report += "---\n\n"
    
    # Add conversation context
    if history:
        report += "## Analysis Context\n\n"
        for entry in history[:5]:  # Last 5 entries
            timestamp = datetime.fromtimestamp(entry['timestamp']).strftime('%H:%M:%S')
            role = entry['role'].upper()
            content = entry['content'][:200] + "..." if len(entry['content']) > 200 else entry['content']
            report += f"**{timestamp} - {role}:** {content}\n\n"
    
    # Add recommendations
    report += """## Recommendations

1. **Address High-Confidence Findings:** Prioritize issues with confidence > 80%
2. **Implement Security Headers:** Add HSTS, CSP, and CORS policies
3. **TLS Configuration:** Update to modern protocols and disable weak ciphers
4. **Regular Monitoring:** Set up continuous security scanning
5. **Input Validation:** Implement comprehensive input sanitization

## Next Steps

1. Review detailed findings above
2. Create remediation tickets for critical issues
3. Implement security improvements
4. Schedule follow-up audit

---
*Report generated by Toonic Security Audit Tool*
"""
    
    return report

def main():
    parser = argparse.ArgumentParser(description="Generate security audit report")
    parser.add_argument("--output", "-o", default="security_audit_report.md", 
                       help="Output file (default: security_audit_report.md)")
    parser.add_argument("--data-dir", default="toonic_data", 
                       help="Data directory (default: toonic_data)")
    parser.add_argument("--goal", default="Security audit of web application", 
                       help="Analysis goal for report header")
    
    args = parser.parse_args()
    
    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        print(f"Error: Data directory {data_dir} does not exist")
        return 1
    
    # Load data
    exchanges = load_exchanges(data_dir)
    history = load_history(data_dir)
    
    if not exchanges and not history:
        print("No analysis data found. Run security audit first.")
        return 1
    
    # Generate report
    report = generate_markdown_report(exchanges, history, args.goal)
    
    # Save report
    output_file = Path(args.output)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"Security audit report generated: {output_file}")
    print(f"Found {len(exchanges)} exchanges and {len(history)} history entries")
    
    return 0

if __name__ == "__main__":
    exit(main())
