#!/bin/bash
# Security Remediation Script for obywatel.bielik.ai
# Usage: sudo ./remediation_script.sh

set -e

echo "🔒 Security Remediation Script for obywatel.bielik.ai"
echo "=================================================="

# Configuration
DOMAIN="obywatel.bielik.ai"
NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"
BACKUP_DIR="/tmp/nginx_backup_$(date +%Y%m%d_%H%M%S)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

# Create backup
print_status "Creating backup of current nginx configuration..."
mkdir -p "$BACKUP_DIR"
if [ -f "$NGINX_CONF" ]; then
    cp "$NGINX_CONF" "$BACKUP_DIR/"
    print_status "Backup created at $BACKUP_DIR"
else
    print_warning "No existing nginx config found at $NGINX_CONF"
fi

# Create security-enhanced nginx configuration
print_status "Creating security-enhanced nginx configuration..."

cat > "$NGINX_CONF" << 'EOF'
# Security-Enhanced Nginx Configuration for obywatel.bielik.ai
# Generated by Security Audit Remediation Script

# HTTP to HTTPS redirect
server {
    listen 80;
    server_name obywatel.bielik.ai www.obywatel.bielik.ai;
    
    # Security headers for redirect
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    
    # Redirect all HTTP traffic to HTTPS
    return 301 https://$server_name$request_uri;
}

# HTTPS server block
server {
    listen 443 ssl http2;
    server_name obywatel.bielik.ai www.obywatel.bielik.ai;
    
    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/obywatel.bielik.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/obywatel.bielik.ai/privkey.pem;
    
    # Modern SSL/TLS Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;
    
    # Security Headers
    add_header Content-Security-Policy "default-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self'" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Server Information
    server_tokens off;
    
    # Root directory
    root /var/www/obywatel.bielik.ai;
    index index.html index.htm;
    
    # Logging
    access_log /var/log/nginx/obywatel.bielik.ai.access.log;
    error_log /var/log/nginx/obywatel.bielik.ai.error.log;
    
    # Static file caching
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        add_header X-Content-Type-Options "nosniff" always;
    }
    
    # Static files with cache busting
    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        add_header X-Content-Type-Options "nosniff" always;
    }
    
    # Main location
    location / {
        try_files $uri $uri/ =404;
        
        # Additional security headers for HTML content
        location ~* \.(html)$ {
            add_header Content-Security-Policy "default-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self'" always;
            add_header X-Frame-Options "DENY" always;
            add_header X-Content-Type-Options "nosniff" always;
        }
    }
    
    # Security - Block access to sensitive files
    location ~ /\. {
        deny all;
    }
    
    location ~ ~$ {
        deny all;
    }
    
    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
EOF

print_status "Nginx configuration updated"

# Test nginx configuration
print_status "Testing nginx configuration..."
if nginx -t; then
    print_status "Nginx configuration test passed"
else
    print_error "Nginx configuration test failed"
    print_status "Restoring backup..."
    if [ -f "$BACKUP_DIR/obywatel.bielik.ai" ]; then
        cp "$BACKUP_DIR/obywatel.bielik.ai" "$NGINX_CONF"
    fi
    exit 1
fi

# Reload nginx
print_status "Reloading nginx..."
systemctl reload nginx

print_status "Nginx reloaded successfully"

# Create content cleanup script
print_status "Creating content cleanup script..."

cat > "/tmp/cleanup_development_urls.sh" << 'EOF'
#!/bin/bash
# Script to clean up development URLs from HTML content

WEB_ROOT="/var/www/obywatel.bielik.ai"
BACKUP_DIR="/tmp/web_content_backup_$(date +%Y%m%d_%H%M%S)"

echo "🧹 Cleaning up development URLs from web content..."

# Create backup
if [ -d "$WEB_ROOT" ]; then
    mkdir -p "$BACKUP_DIR"
    cp -r "$WEB_ROOT" "$BACKUP_DIR/"
    echo "Backup created at $BACKUP_DIR"
fi

# Replace localhost URLs with production URLs
find "$WEB_ROOT" -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) -exec sed -i 's|localhost:8126|obywatel.bielik.ai|g' {} +

echo "Development URLs replaced with production URLs"

# Update specific meta tags if they exist
find "$WEB_ROOT" -name "*.html" -exec sed -i 's|http://localhost:8126/|https://obywatel.bielik.ai/|g' {} +

echo "Meta tags updated"

echo "✅ Content cleanup completed"
EOF

chmod +x "/tmp/cleanup_development_urls.sh"

print_status "Content cleanup script created at /tmp/cleanup_development_urls.sh"

# Create security monitoring script
print_status "Creating security monitoring script..."

cat > "/tmp/security_monitoring.sh" << 'EOF'
#!/bin/bash
# Security monitoring script for obywatel.bielik.ai

DOMAIN="obywatel.bielik.ai"
LOG_FILE="/var/log/security_monitoring.log"

echo "🔍 Running security monitoring for $DOMAIN..."

# Function to log with timestamp
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

# Check SSL certificate
log_message "Checking SSL certificate..."
if openssl s_client -connect "$DOMAIN":443 -servername "$DOMAIN" </dev/null 2>/dev/null | grep -q "Verify return code: 0 (ok)"; then
    log_message "✅ SSL certificate is valid"
else
    log_message "❌ SSL certificate issue detected"
fi

# Check security headers
log_message "Checking security headers..."
HEADERS=$(curl -s -I "https://$DOMAIN" 2>/dev/null)

SECURITY_HEADERS=(
    "content-security-policy"
    "x-frame-options"
    "x-content-type-options"
    "referrer-policy"
    "strict-transport-security"
)

for header in "${SECURITY_HEADERS[@]}"; do
    if echo "$HEADERS" | grep -qi "$header"; then
        log_message "✅ $header header present"
    else
        log_message "❌ $header header missing"
    fi
done

# Check for development URLs
log_message "Checking for development URLs..."
if curl -s "https://$DOMAIN" 2>/dev/null | grep -q "localhost"; then
    log_message "❌ Development URLs still present"
else
    log_message "✅ No development URLs found"
fi

# Check HTTPS redirect
log_message "Checking HTTPS redirect..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://$DOMAIN")
if [ "$HTTP_STATUS" = "301" ]; then
    log_message "✅ HTTPS redirect working"
else
    log_message "❌ HTTPS redirect not working (status: $HTTP_STATUS)"
fi

log_message "Security monitoring completed"
echo "Log file: $LOG_FILE"
EOF

chmod +x "/tmp/security_monitoring.sh"

print_status "Security monitoring script created at /tmp/security_monitoring.sh"

# Create cron job for security monitoring
print_status "Setting up security monitoring cron job..."

(crontab -l 2>/dev/null; echo "0 6 * * * /tmp/security_monitoring.sh") | crontab -

print_status "Security monitoring scheduled daily at 6:00 AM"

# Summary
echo ""
echo "🎉 Security remediation completed!"
echo "=================================="
echo ""
echo "✅ Nginx configuration updated with security headers"
echo "✅ SSL/TLS hardening applied"
echo "✅ Content cleanup script created"
echo "✅ Security monitoring script created"
echo "✅ Daily monitoring scheduled"
echo ""
echo "Next steps:"
echo "1. Run content cleanup: /tmp/cleanup_development_urls.sh"
echo "2. Test security headers: curl -I https://obywatel.bielik.ai"
echo "3. Run security monitoring: /tmp/security_monitoring.sh"
echo "4. Check logs: /var/log/security_monitoring.log"
echo ""
echo "Backup location: $BACKUP_DIR"
echo "Configuration file: $NGINX_CONF"
echo ""
print_status "Remediation script completed successfully!"
